
class UserException(Exception):
    pass


class PlaceException(Exception):
    pass
